# Generated by Django 4.1a1 on 2022-05-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject_massage', models.CharField(blank=True, db_index=True, max_length=255)),
                ('massage', models.TextField(blank=True)),
            ],
        ),
    ]
